### ISSUE TITLE
Use PathBuf for paths

### ISSUE THREAD

**Issue by Aetf** [1sra3l/xdgkit#1]
This looks like exactly what I need, thanks for doing this!

I'm wondering why `String` instead of `PathBuf` for all paths?

**Comment by 1sra3l** [comment]
@Aetf I just used String type initially because the idea is to make both a library and a command-line tool, so I was mostly thinking about printing statements, rather than making it a `PathBuf` for library use.  Would you rather have all the "basedir" items return PathBuf?

**Comment by Aetf** [comment]
I mostly use the `icon_finder` module, which also involves paths to icons. It'd be great if various functions would accept `Path` and return `Path`/`PathBuf` as needed.

It also makes it easier to distinguish between icon names and paths to image files.

**Comment by 1sra3l** [comment]
@Aetf 2.0.3 should do what you need!  Let me know

**Comment by Aetf** [comment]
Just FYI, since changing to PathBuf is a breaking API change, you'd better bump the major version if you want to follow Semantic Versioning.

**Comment by 1sra3l** [comment]
@Aetf I thought about that earlier, but was wondering if you would prefer a simple `PathBuf`, instead of an `Option<PathBuf>`  since you can simply call `Pathbuff::exists()`?

If you think that is more sensible I'd rather make it what everyone else will expect/want.  I'd rather it be usable by others in case I never build the project I am making it for :rofl:

**Comment by Aetf** [comment]
I think `Option<PathBuf>` makes sense. If just returning `PathBuf`, you have to specifically document that the path may not exist. While the current design encodes that into the return type, which I feel is better.

**Comment by 1sra3l** [comment]
@Aetf Okay bumped to version 3.0.0  thanks!
