### ISSUE TITLE
icon theme doesn't allow overriding a subset of an existing theme's icons in a custom directory

### ISSUE THREAD

**Issue by daym** [1sra3l/xdgkit#3]
UNIX tradition allows you to override stuff in /usr/local that was there in /usr already, simulating a unionfs.

As far as I can tell, `icon_finder.rs` doesn't support that. A theme seems to be identified with just one xdg (base) directory, making such overrides impossible.

**Comment by 1sra3l** [comment]
Hi @daym I mostly just based this code off of the psuedo code [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup) but I am glad for any contributions to make it work more like others want, especially since I have not had much time for programming lately.  thanks!
